### ISSUE TITLE
write a XeTeX compatible font spec parser

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/ufy#19]
@khaledhosny suggested that a XeTeX compatible font spec parser would be simpler and more useful than luaotfload. It could be used In conjunction with a font searching mechanism, for which we are planning to use [luafontmanager](https://github.com/ufytex/luafontmanager).

This library might be the best place for it. We can hook it up with a function that can locate fonts using luafontmanager, and then load it using `fontloader.load` (or some other way later)

The XeTeX `\font` command is documented in the XeTeX manual Part I.

**Comment by deepakjois** [comment]
@khaledhosny do you know where I can find the font spec parsing code in XeTeX? I wanted to refer to it before writing a similar one in Lua, maybe using lpeg.

**Comment by khaledhosny** [comment]
Start with https://sourceforge.net/p/xetex/code/ci/master/tree/source/texk/web2c/xetexdir/XeTeX_ext.c#l1151

**Comment by deepakjois** [comment]
@khaledhosny I started to write the parser here: https://github.com/deepakjois/ufy/blob/master/src/ufy/fontspec.lua

Check the spec [here](https://github.com/deepakjois/ufy/blob/master/spec/fontspec_spec.lua) for all the cases that are passing right now.

I am a bit confused about the font options, so that is not implemented yet. I am thinking, it should be enough to support the `/B`, `/I`, `/BI` and `/IB` options.

I have also implemented the font features as either strings that turn on features (`-smcp`), turn off features (`+smcp`), features that take values (`+aalt=1`, ignored when preceded by `-`), and features that are just simply key value pairs (`language=arab`, `script=urd` or even something like `harfbuzz=on`). The ability to accept arbitrary key value pairs can come in handy to pass some options to the layout engine, like turning Harfbuzz/bidi off etc.

**Comment by khaledhosny** [comment]
Thanks, looks good. I don’t speak lpeg so I can’t comment on actual code. As for font options, XeTeX ignores font options it does not recognize, so I think this parser should do the same instead of ignoring the whole spec. It might be also a good idea to support `OT` (and the deprecated `ICU`), `GR`, and `AAT` since HarfBuzz supports the three shapers and fontspec package makes use of these options. It might even be better to just return a table of font options and leave it to the consuming code how to interpret them.

**Comment by deepakjois** [comment]
Ok I made some changes:

* All documented options except `/S=x` are supported now. I am not supporting `/S=x` option right now, because it’s a bit awkward to parse since it takes an argument But if it is important, it’s not impossible to support it
* We ignore unknown font options. It is pretty easy to enable support for a font options [here](https://github.com/deepakjois/ufy/blob/88409d5c1864667fdc525271a3efff88246a2519/src/ufy/fontspec.lua#L40)

**Comment by khaledhosny** [comment]
`S=x` is used by fontspec as well (when `OpticalSize` option is used).

**Comment by deepakjois** [comment]
On Thu, Jun 8, 2017 at 8:12 PM, Khaled Hosny <notifications@github.com>
wrote:

> S=x is used by fontspec as well (when OpticalSize option is used).


Ok in that case, I will make the changes to the parser after all.

However, I am still not clear on how this functionality will work with
fontspec. Is the goal to build some sort of drop-in replace to fontspec? Or
will fontspec be able to use this  to load fonts?

**Comment by deepakjois** [comment]
option for optical size is now supported as well.

**Comment by khaledhosny** [comment]
The parser will be hooked to the font loading callback on LuaTeX, so it replaces part of luaotfload. This parser, luafontmanager, and ufylayout should together build a more or less luaotfload replacement. I think fontspec will need to be made aware for this, but the advantage of using XeTeX compatible syntax is making fontspec changes regarding font loading as minimal as possible. We might need to emulate a few XeTeX primitives as well to get fontspec fully functional without much fiddling with TeX macros.

**Comment by deepakjois** [comment]
Ok…thanks for the clarification. I have to admit I am not very sure how to get started on all of the above stuff. Maybe you could open more specific issues against the relevant repo where the code to achieve the functionality you mention, will lie. I will work on them once there is more clarity around what changes are required.

I assume the parser can now be considered done. I will close this issue.
