### ISSUE TITLE
Add cmark example

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/ufy#2]
Typeset a Markdown document into LuaTex

**Comment by michal-h21** [comment]
What about [Lunamark](https://github.com/jgm/lunamark)? It depends only on LPEG and it has already been used with LuaTeX (see [Markdown](https://ctan.org/pkg/markdown) package).

Also, what about XML support? See my fork of [LuaXML](https://github.com/michal-h21/LuaXML) for example. It is in pure Lua. I've recently added simple DOM and CSS selector libraries. If we could add support for full CSS, it would be possible to typeset web pages, Epub files, etc.

**Comment by deepakjois** [comment]
Since I filed this issue, I came to the conclusion that it would be better if the _ufy_ Luarocks module itself was kept free of any dependencies, other than the absolutely necessary ones. _ufy_ currently has three dependencies (datafile, luafilesystem and lua-path), and I do not intend to add to it.

Notice that we need to install the additional packages _luaharfbuzz_ and _luabidi_ explicitly before we can run the bidi example. This is deliberate. If someone would like to use _ufy_ for some other purpose, it would be unnecessarily complicated for them to go through the installation of these modules, which depend on external libraries like Harfbuzz and ucdn.

For supporting XML or Markdown formats, it should just be a matter of pulling the dependency in your Lua script, and just using it. For more complicated scenarios, you can create a separate module like _ufy-markdown_, _ufy-xml_ or _ufy-docbook_ etc. I imagine I would need to create a module named _ufy-harfbuzz_ or _ufy-bidi_ later, for my requirements.

Lunamark and [cmark-lua] are from the same author. I prefer cmark-lua because of two reasons: 1. it is a parser for [CommonMark], which is a ‘strongly defined’ spec for Markdown, and 2. It exposes a nice API for parsing markdown, which allows you to walk the nodes and process them hierarchically (see the README of the project to see what I mean).

[cmark-lua]:https://github.com/jgm/cmark-lua
[CommonMark]:http://commonmark.org/

Having said that, you could always use Lunamark if that’s what you wanted. It’s just another LuaRocks module that can be imported into your script :).

**Comment by deepakjois** [comment]
Added a crude example using [cmark-lua](https://github.com/jgm/cmark-lua) in a2cf80948ce988133523cbcc1474add1eb9fb57c
