### ISSUE TITLE
Add example using luabidi and luaharfbuzz

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/ufy#3]
We should be able to take a multilingual string, and:
- Run the bidi algorithm
- Itemize it according to script
- Shape it using harfbuzz

and finally, send the final output to the luatex node building routines

**Comment by deepakjois** [comment]
ICU code for reference: http://icu-project.org/apiref/icu4c/ubidi_8h.html

Apart from that there is libraqm as well.

**Comment by deepakjois** [comment]
A basic working example is up: https://github.com/deepakjois/ufy/blob/master/examples/bidi.lua

Now need to generalize it and incorporate script itemization.

**Comment by deepakjois** [comment]
@michal-h21, maybe you are interested in the code above. It demonstrates what I was talking about earlier, regarding doing reordering and shaping before generating the node list.

**Comment by michal-h21** [comment]
@deepakjois thanks, it is indeed interesting. I tried to install Ufy, it executed `ufy --setup`, but when I try to execute some examples, it fails:

```
Checking if luatex is present…

/home/michal/.ufy/luatex --shell-escape --lua=/home/michal/prg/ufy/lua52/lib/luarocks/rocks/ufy/scm-1/config/ufy_pre_init.lua --jobname=bidi --ini '\catcode`\{=1' '\catcode`\}=2' '\directlua{ufy.init()}' '\directlua{dofile("bidi.lua")}' '\end'

Could not locate config. Aborting…
```

Anyway, I've took a look at the code and I have few questions:

- what is the purpose of double use of `buf:reverse()`?

```
  buf:add_codepoints(reordered)
  buf:reverse()
  harfbuzz.shape(hb_font, buf, { direction = "RTL" })
  buf:reverse()
```

Is it because of `RTL`?

- isn't the next code inefficient?:

       local char = font.getfont(current_font).backmap[v.codepoint]

it is executed in a loop and according to LuaTeX manual:

> Note that at the moment, each access to the font.fonts or call to font.getfont creates a Lua table for the whole font. This process can be quite slow. In a later version of LuaTEX, this interface will change (it will start using userdata objects instead of actual tables).

**Comment by deepakjois** [comment]
>  but when I try to execute some examples, it fails:

I will investigate this. I encountered this error a while ago due to the LuaTeX interpreter not being able to execute some shell commands that LuaRocks runs to locate its own config. I thought I had fixed it, but looks like it is not working on your setup. Is this Linux?

Regarding your comments, I got the example to work just yesterday. I need to clean it up a lot.

> what is the purpose of double use of buf:reverse()?

Yes is it due to to RTL.  The example code is currently hardcoded for RTL. That needs to be cleaned up as well. 

`bidi.get_visual_reordering` gets the visually reordered string after applying bidi algorithm. But Harfbuzz expects the rightmost character to be at the first position. The shaping output is in LTR order, but LuaTeX is in ‘TRT’ direction, so another reversal needs to happen.

There may be other ways to achieve the same thing without too much reversal. Maybe the Harfbuzz API has some settings.

> isn't the next code inefficient?:

It probably is inefficient. Like I said, a lot of cleanup is required. I was just trying to make the example work.

Here is what shows up in my PDF file once everything is working:

![screenshot 2017-01-26 07 52 06](https://cloud.githubusercontent.com/assets/5342/22317857/714596f4-e39c-11e6-88ad-0400991815e6.png)

**Comment by deepakjois** [comment]
@michal-h21 could you please try doing `eval $(luarocks path)` before you run ufy. I have added that to the instructions now. That may solve the issue.

And for running the examples, you will need additional dependencies installed:

```
luarocks install compat53 luabidi luaharfbuzz
```

I wanted to keep those dependencies independent of the ufy program.

**Comment by deepakjois** [comment]
This is what I get on Ubuntu 14.04 (running inside Windows subsystem for Linux):

```
deepak@DESKTOP-KBDVN6I:~/ufy/examples$ ufy bidi.lua
Checking if luatex is present…

/home/deepak/.ufy/luatex --shell-escape --lua=/home/deepak/lua52/lib/luarocks/rocks/ufy/scm-1/config/ufy_pre_init.lua --jobname=bidi --ini '\catcode`\{=1' '\catcode`\}=2' '\directlua{ufy.init()}' '\directlua{dofile("bidi.lua")}' '\end'

This is LuaTeX, Version 1.0.0 (TeX Live 2017/dev)  (INITEX)
 system commands enabled.
…
```

**Comment by michal-h21** [comment]
@deepakjois I've tried to install Ufy on my work computer with Fedora 21 and it works. The problem with this machine is that `harfbuzz` library is too old and it doesn't work with `luaharfbuzz`:

        /home/mint/prg/hererocks/lua52/lib/lua/5.2/luaharfbuzz.so: undefined symbol: hb_buffer_get_cluster_level

Anyway, I will try the installation from scratch on my home PC tonight, I probably just omitted some step.

**Comment by deepakjois** [comment]
Yes, I had that issue with old Harfbuzz on Ubuntu 14.04. I just compiled a fresh one from the source (the _.tar.bz2_ from the [releases page](https://github.com/behdad/harfbuzz/releases)) by doing

```
./configure --with-freetype=no --with-gobject=no
```

This ensures it doesnt try to pull in any other dependencies.

**Comment by michal-h21** [comment]
Thanks my system is really old, because even `autoconf` failed with syntax errors in `configure.ac`, I will get new computer with Fedora 25 soon, so it is probably not worth to try to fix that :)

**Comment by michal-h21** [comment]
I've just got Ufy to work on my home machine, `eval $(luarocks path)` did the trick.

**Comment by deepakjois** [comment]
Closing this, because I have added a bidi example to the project already.

I will continue to clean up and enhance the bidi example as I experiment more, but more extensive support for bidi typesetting belongs in another module.
